controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

connexion:
        path: /connexion
        controller: App\Controller\ConnexionController::connexion
