controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

bonjour:
        path: /bonjour
        controller: App\Controller\BonjourController::bonjour
