controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route de la page connexion 
connexion:
        path: /
        controller: App\Controller\ConnexionController::appelConnexionForm

#route de la page modification 
modif:
        path: /modif/{id}
        controller: App\Controller\ModifController::appelFormModif
        methods: [GET]
        requirements:
                id: '\d+'

modifEmploye:
        path: /modifEmploye/{id}
        controller: App\Controller\ModifEmployeController::appelFormModif
        methods: ['GET', 'POST']

#route de la page suppression
# route pour supprimer 
suppr:
        path: /suppr/{id}
        controller: App\Controller\SuppressionController::appelFormSuppression
        methods: [GET]


# route pour valider et exécuter la suppression
supprConfirm:
        path: /suppr/suppression/{id}
        controller: App\Controller\SuppressionController::suppression
        methods: [POST]