controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route de la page connexion 
connexion:
        path: /
        controller: App\Controller\ConnexionController::appelConnexionForm

#route de la page modification 
modif:
        path: /modif
        controller: App\Controller\ModifController::appelFormModif

#route de la page suppression
# route pour afficher la page de confirmation
suppr:
        path: /suppr/{id}
        controller: App\Controller\SuppressionController::appelFormSuppression
        methods: [GET]

# route pour valider et exécuter la suppression
supprConfirm:
        path: /suppr/suppression/{id}
        controller: App\Controller\SuppressionController::suppression
        methods: [POST]