<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD1VvDxn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD1VvDxn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD1VvDxn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD1VvDxn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD1VvDxn\App_KernelDevDebugContainer([
    'container.build_hash' => 'D1VvDxn',
    'container.build_id' => 'c8cb6aeb',
    'container.build_time' => 1741592536,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD1VvDxn');
