
services:
  database:
    image: mysql:8
    container_name: bhlm-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bhlm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin
    container_name: symfony-phpmyadmin
    restart: always
    environment:
      PMA_HOST: bhlm-database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
